name: iOS Build Test

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [main, develop]
    paths:
      - "apps/mobile/**"
      - ".github/workflows/ios-build.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "apps/mobile/**"
      - ".github/workflows/ios-build.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ios-build:
    name: iOS Build Test
    runs-on: macos-15 # Use macOS 15 with Xcode 16 for Swift 6 support
    timeout-minutes: 30

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Prebuild iOS
        working-directory: apps/mobile
        run: |
          # Generate native iOS project
          npx expo prebuild --platform ios --clean

      - name: Clean pod cache and prepare iOS build
        working-directory: apps/mobile
        run: |
          # Clean pod cache to avoid version conflicts
          cd ios
          pod cache clean --all
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf Pods
          rm -f Podfile.lock

      - name: Install pods
        working-directory: apps/mobile/ios
        run: |
          # Install CocoaPods dependencies
          pod install --repo-update

      - name: Check iOS build environment
        working-directory: apps/mobile/ios
        run: |
          # Check Xcode and workspace
          ls -la
          xcodebuild -version
          xcodebuild -list -workspace ichizen.xcworkspace

      - name: Build iOS app for simulator (basic)
        working-directory: apps/mobile/ios
        run: |
          # Build with minimal targets first
          xcodebuild \
            -workspace ichizen.xcworkspace \
            -scheme ichizen \
            -configuration Debug \
            -sdk iphonesimulator \
            -arch arm64 \
            -derivedDataPath build \
            build-for-testing \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES

      - name: Archive iOS build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-${{ github.sha }}
          path: apps/mobile/ios/build/Build/Products/*/*.app
          retention-days: 7

      - name: Summary
        if: always()
        run: |
          echo "## iOS Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Build Status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ job.status }}" == "success" ]; then
            echo "- Artifact: ios-build-${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          fi
