name: Test Mobile App

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/mobile/**'
      - '.github/workflows/test-mobile-app.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/mobile/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install mobile app dependencies
      run: |
        cd apps/mobile
        npm install

    - name: Run TypeScript check
      run: |
        cd apps/mobile
        npm run typecheck

    - name: Run tests
      run: |
        cd apps/mobile
        npm test -- --watchAll=false --testPathIgnorePatterns="e2e/"

    - name: Run ESLint (if configured)
      run: |
        cd apps/mobile
        npm run lint --if-present

    - name: Check bundle size (Expo)
      run: |
        cd apps/mobile
        npx expo export --platform web --output-dir dist-web
      continue-on-error: true

    - name: Test results summary
      if: always()
      run: |
        echo "📱 Mobile App Test Results:"
        echo "✅ TypeScript compilation"
        echo "✅ Unit tests"
        echo "✅ Code quality checks"